name: auto-deploy

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  auto-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18.12.1'

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # 临时加大可用内存
      - name: Increse Mem
        run: pnpm i increase-memory-limt && cross-env LIMIT=2048 increase-memory-limit

      # 运行构建脚本
      - name: Build site
        run: pnpm build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 部署到 gh-pages 分支
          publish_dir: ./docs/.vuepress/dist
          # cname: xxx.xxx
